version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: roles_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


  nextjs-app:
    build:
      context: ./nextjs-app
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./nextjs-app:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
    command: pnpm dev

  # nextjs-app:
  #   build:
  #     context: ./nextjs-app
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - app-network
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  frontend:
    build:
      context: ./fe-mng
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - be-fastpy
      - be-nestjs
    networks:
      - app-network

  be-fastpy:
    build:
      context: ./be-fastpy
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - PORT=9090
    networks:
      - app-network

  be-nestjs:
    build:
      context: ./be-nestjs
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./be-nestjs/.env

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
